# Generated by Django 3.1.2 on 2020-12-20 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201111_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollows',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='userfollows',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
