# Generated by Django 3.1.4 on 2020-12-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201220_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileDailyMeal',
        ),
    ]
