# Generated by Django 3.1.4 on 2021-02-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210107_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='GKI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucoze', models.FloatField()),
                ('ketones', models.FloatField()),
                ('gki', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gki', to='profiles.profile')),
            ],
        ),
    ]
