# Generated by Django 3.1.7 on 2021-04-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GKI',
        ),
    ]
