# Generated by Django 3.1.7 on 2021-04-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210427_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target',
            field=models.CharField(choices=[('redukcja', 'Redukcja wagi'), ('utrzymanie', 'Utrzymanie wagi'), ('masa', 'Zwiększenie masy')], default='utrzymanie', max_length=10, verbose_name='Cel'),
        ),
    ]
