# Generated by Django 3.1.4 on 2021-02-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210202_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerReply',
        ),
    ]
