# Generated by Django 3.1.7 on 2021-04-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210427_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesystem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_question', to='questions.question'),
        ),
    ]
