# Generated by Django 3.1.2 on 2020-12-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='recipe',
        ),
    ]
