# Generated by Django 3.1.4 on 2020-12-30 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeevent',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recipeevent',
            name='date',
            field=models.DateField(),
        ),
    ]
