# Generated by Django 3.1.4 on 2020-12-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201230_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeevent',
            old_name='meal',
            new_name='recipe',
        ),
    ]
