# Generated by Django 3.1.4 on 2020-12-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_user'),
        ('recipes', '0007_auto_20201230_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeevent',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredients', to='food.food'),
        ),
    ]
