# Generated by Django 3.1.4 on 2021-01-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210101_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
