# Generated by Django 3.1.4 on 2021-01-06 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='images',
            field=models.ImageField(blank=True, upload_to='recipes', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.DeleteModel(
            name='FavouriteMeal',
        ),
    ]
