# Generated by Django 3.1.4 on 2021-02-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20210202_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('szt', 'szt')], max_length=3),
        ),
    ]
