# Generated by Django 3.1.4 on 2021-02-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20210202_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeevent',
            name='description',
            field=models.CharField(default='Meal', max_length=15),
        ),
    ]
