# Generated by Django 3.1.4 on 2021-02-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_recipeevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
