# Generated by Django 3.1.4 on 2021-02-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20210216_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeevent',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
