# Generated by Django 3.1.4 on 2021-02-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_auto_20210216_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeevent',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.RecipeIngredients'),
        ),
    ]
