# Generated by Django 3.1.4 on 2021-02-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_remove_recipeevent_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeevent',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.recipe'),
        ),
    ]
