# Generated by Django 3.1.4 on 2021-03-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20210319_0942'),
        ('recipes', '0027_auto_20210313_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit', to='food.foodweight'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
