# Generated by Django 3.1.4 on 2021-03-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_auto_20210319_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='value',
        ),
    ]
