# Generated by Django 3.1.4 on 2021-03-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_weight'),
        ('recipes', '0029_remove_like_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='profiles.Profile'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
