# Generated by Django 3.1.4 on 2021-03-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_auto_20210319_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='quantity',
            field=models.FloatField(db_index=True, default=100),
        ),
    ]
