# Generated by Django 3.1.4 on 2021-03-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_auto_20210321_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='quantity',
            field=models.IntegerField(db_index=True, default=100),
        ),
    ]
