# Generated by Django 3.1.7 on 2021-05-06 17:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20210413_1406'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('recipes', '0032_auto_20210321_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created', 'title')},
        ),
        migrations.AddField(
            model_name='recipe',
            name='content',
            field=django_editorjs.fields.EditorJsField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='images',
            field=models.ImageField(default='recipes/default.png', upload_to='recipes', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='portions',
            field=models.PositiveIntegerField(default=1, verbose_name='Ilość porcji'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prepare_time',
            field=models.TimeField(verbose_name='Czas przygotowania'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Czy chcesz publikować post?'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Tagi należy odzielić od siebie przecinkiem', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tagi'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='recipeevent',
            name='description',
            field=models.CharField(db_index=True, default='Posiłek', max_length=15),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredients', to='food.food', verbose_name='Składnik'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='quantity',
            field=models.IntegerField(db_index=True, default=100, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit', to='food.foodweight', verbose_name='Rodzaj'),
        ),
    ]
