# Generated by Django 3.1.2 on 2020-11-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('alcohol', 'Alcohol'), ('dairy', 'Dairy'), ('eggs', 'Eggs'), ('fats', 'Fats'), ('fish', 'Fish'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('meat', 'Meat'), ('others', 'Others'), ('seeds and nuts', 'Seeds and Nuts'), ('vegetables', 'Vegetables')], max_length=50)),
                ('kcal', models.FloatField(blank=True, null=True)),
                ('proteins', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fats', models.FloatField()),
                ('saturated_fats', models.FloatField(blank=True, default=0, null=True)),
                ('fiber', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
