# Generated by Django 3.1.4 on 2021-02-02 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(blank=True, choices=[('szt', 'Sztuki'), ('g', 'Gramy'), ('ml', 'Mililitry')], default='g', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.measurementquantity')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.measurementunits')),
            ],
        ),
    ]
