# Generated by Django 3.1.4 on 2021-02-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210202_1539'),
        ('recipes', '0015_auto_20210202_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='MeasurementQuantity',
        ),
        migrations.DeleteModel(
            name='MeasurementUnits',
        ),
    ]
