# Generated by Django 3.1.4 on 2021-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20210303_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ndb_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
