# Generated by Django 3.1.4 on 2021-03-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_food_ndb_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ash',
            field=models.FloatField(default=0),
        ),
    ]
