# Generated by Django 3.1.4 on 2021-03-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_food_ash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ndb_no',
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('produkty mleczne i jajeczne', 'Produkty mleczne i jajeczne'), ('produkty wolowe', 'Produkty wołowe'), ('ziarna zboz i makaron', 'Ziarna zbóż i makaron'), ('tluszcze i oleje', 'Tłuszcze i oleje'), ('produkty z ryb i skorupiakow', 'Produkty z ryb i skorupiaków'), ('owoce', 'Owoce'), ('produkty z jagnieciny, cieleciny i dziczyzny', 'Produkty z jagnięciny, cielęciny i dziczyzny'), ('rosliny straczkowe i produkty z roslin straczkowych', 'Rośliny strączkowe i produkty z roślin strączkowych'), ('ziarna i orzechy', 'Ziarna i orzechy'), ('produkty wieprzowe', 'Produkty wieprzowe'), ('produkty drobiowe', 'Produkty drobiowe'), ('przyprawy i ziola', 'Przyprawy i zioła'), ('warzywa i produkty warzywne', 'Warzywa i produkty warzywne'), ('wedliny', 'Wędliny'), ('pieczywo', 'Pieczywo'), ('przetwory rybne', 'Przetwory rybne')], max_length=80),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='FoodWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_description', models.CharField(max_length=30)),
                ('gram', models.FloatField()),
                ('food_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.food')),
            ],
        ),
    ]
